version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Pre-build phase"
      # - pytest -q

  build:
    commands:
      - echo "Preparing deployment artifact..."
      - chmod +x scripts/*.sh
      - test -f appspec.yml
      - ls -la
      - ls -la scripts

artifacts:
  files:
    - appspec.yml
    - app.py
    - requirements.txt
    - templates/**/*
    - static/**/*
    - scripts/**/*
  discard-paths: no